linters:
  enable-all: true
  disable:
    - lll
    - varnamelen
    - wrapcheck
    - goerr113
    - gochecknoglobals
    - exhaustivestruct
    - exhaustruct
    - cyclop
    - funlen
    - gocognit
    - gocyclo
    - testpackage
    - nestif  # FIXME
    - gomnd  # FIXME

linters-settings:
  tagliatelle:
    case:
      rules:
        json: snake
