linters:
  enable-all: true
  disable:
    - lll
    - varnamelen
    - wrapcheck
    - goerr113
    - gochecknoglobals
    - exhaustivestruct
    - exhaustruct
    - cyclop
    - funlen
    - gocognit
    - gocyclo
    - nestif  # FIXME
    - wsl  # FIXME
    - testpackage  # FIXME
    - paralleltest  # FIXME
    - nlreturn  # FIXME
    - ifshort  # FIXME
    - gomnd  # FIXME

linters-settings:
  tagliatelle:
    case:
      rules:
        json: snake
