name: Continuous Integration

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [1.19]

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: make dep

    - name: Build
      run: make build
  
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [1.19]

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: make dep

    - name: Test
      run: make test


  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go: [1.19]

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Check lints
      run: sudo make lint
